version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hackerman
      MYSQL_DATABASE: local
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    ports:
      - 3306:3306
volumes:
  db_data: { }